### ISSUE TITLE
Export to STL

### ISSUE THREAD

**Issue by pingwes** [Munanni/HUnet#2]
How do we export the phase to a STL?

Wes

**Comment by Moon-Hwan** [comment]
The phase corresponds to the time delay applied by different lens thicknesses fabricated with converted STL files. So, the phase map needs to be converted to a thickness map with some formula.
The thickness map can be voxelized and converted to an STL file.
The details are addressed in my paper below.
M. H. Lee, H. M. Lew, S. Youn, T. Kim, and J. Y. Hwang, "Deep learning-based framework for fast and accurate acoustic hologram generation," in IEEE Transactions on Ultrasonics, Ferroelectrics, and Frequency Control, 2022, doi: 10.1109/TUFFC.2022.3219401.
